"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Property = exports.Item = exports.Player = exports.Page = exports.Book = void 0;
var book_1 = require("./classes/book");
Object.defineProperty(exports, "Book", { enumerable: true, get: function () { return book_1.Book; } });
var item_1 = require("./classes/item");
Object.defineProperty(exports, "Item", { enumerable: true, get: function () { return item_1.Item; } });
var page_1 = require("./classes/page");
Object.defineProperty(exports, "Page", { enumerable: true, get: function () { return page_1.Page; } });
var player_1 = require("./classes/player");
Object.defineProperty(exports, "Player", { enumerable: true, get: function () { return player_1.Player; } });
var property_1 = require("./classes/property");
Object.defineProperty(exports, "Property", { enumerable: true, get: function () { return property_1.Property; } });
